base_url = "https://code.dev"
title = "Code"
description = "Headless & scalable Git forge backed by a write-ahead log in object storage."
default_language = "en"
compile_sass = true
build_search_index = false
generate_feeds = false

[markdown.highlighting]
theme = "github-light"
